name: RAG Quality Gate

on:
  pull_request:
    branches: [ "main" ]

jobs:
  evaluate:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    # - name: Build Vector Database
    #   run: python populate_db.py

    - name: Run Ragas Evaluation
      env:
        # This securely injects the secret you saved in Step 2 into the script
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        
        # Ensure your script knows where to look for the DB
        CHROMA_PATH: "chroma" 
      run: |
        python evaluate_rag.py